// Vendored from kata-containers/src/runtime/protocols/cache/cache.proto
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cache.proto

package cachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcVMConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,2,opt,name=AgentConfig,proto3" json:"AgentConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcVMConfig) Reset() {
	*x = GrpcVMConfig{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcVMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcVMConfig) ProtoMessage() {}

func (x *GrpcVMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcVMConfig.ProtoReflect.Descriptor instead.
func (*GrpcVMConfig) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcVMConfig) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GrpcVMConfig) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type GrpcVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hypervisor    []byte                 `protobuf:"bytes,2,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	ProxyPid      int64                  `protobuf:"varint,3,opt,name=proxyPid,proto3" json:"proxyPid,omitempty"`
	ProxyURL      string                 `protobuf:"bytes,4,opt,name=proxyURL,proto3" json:"proxyURL,omitempty"`
	Cpu           uint32                 `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        uint32                 `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	CpuDelta      uint32                 `protobuf:"varint,7,opt,name=cpuDelta,proto3" json:"cpuDelta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcVM) Reset() {
	*x = GrpcVM{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcVM) ProtoMessage() {}

func (x *GrpcVM) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcVM.ProtoReflect.Descriptor instead.
func (*GrpcVM) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcVM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrpcVM) GetHypervisor() []byte {
	if x != nil {
		return x.Hypervisor
	}
	return nil
}

func (x *GrpcVM) GetProxyPid() int64 {
	if x != nil {
		return x.ProxyPid
	}
	return 0
}

func (x *GrpcVM) GetProxyURL() string {
	if x != nil {
		return x.ProxyURL
	}
	return ""
}

func (x *GrpcVM) GetCpu() uint32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *GrpcVM) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *GrpcVM) GetCpuDelta() uint32 {
	if x != nil {
		return x.CpuDelta
	}
	return 0
}

type GrpcStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Vmstatus      []*GrpcVMStatus        `protobuf:"bytes,2,rep,name=vmstatus,proto3" json:"vmstatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStatus) Reset() {
	*x = GrpcStatus{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStatus) ProtoMessage() {}

func (x *GrpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStatus.ProtoReflect.Descriptor instead.
func (*GrpcStatus) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GrpcStatus) GetVmstatus() []*GrpcVMStatus {
	if x != nil {
		return x.Vmstatus
	}
	return nil
}

type GrpcVMStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Cpu           uint32                 `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        uint32                 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcVMStatus) Reset() {
	*x = GrpcVMStatus{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcVMStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcVMStatus) ProtoMessage() {}

func (x *GrpcVMStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcVMStatus.ProtoReflect.Descriptor instead.
func (*GrpcVMStatus) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcVMStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GrpcVMStatus) GetCpu() uint32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *GrpcVMStatus) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x05cache\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\fGrpcVMConfig\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12 \n" +
	"\vAgentConfig\x18\x02 \x01(\fR\vAgentConfig\"\xb6\x01\n" +
	"\x06GrpcVM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"hypervisor\x18\x02 \x01(\fR\n" +
	"hypervisor\x12\x1a\n" +
	"\bproxyPid\x18\x03 \x01(\x03R\bproxyPid\x12\x1a\n" +
	"\bproxyURL\x18\x04 \x01(\tR\bproxyURL\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\rR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\rR\x06memory\x12\x1a\n" +
	"\bcpuDelta\x18\a \x01(\rR\bcpuDelta\"O\n" +
	"\n" +
	"GrpcStatus\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12/\n" +
	"\bvmstatus\x18\x02 \x03(\v2\x13.cache.GrpcVMStatusR\bvmstatus\"J\n" +
	"\fGrpcVMStatus\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\rR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\rR\x06memory2\xe6\x01\n" +
	"\fCacheService\x125\n" +
	"\x06Config\x12\x16.google.protobuf.Empty\x1a\x13.cache.GrpcVMConfig\x122\n" +
	"\tGetBaseVM\x12\x16.google.protobuf.Empty\x1a\r.cache.GrpcVM\x123\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x11.cache.GrpcStatus\x126\n" +
	"\x04Quit\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB5Z3github.com/maci0/katamaran/internal/factory/cachepbb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cache_proto_goTypes = []any{
	(*GrpcVMConfig)(nil),  // 0: cache.GrpcVMConfig
	(*GrpcVM)(nil),        // 1: cache.GrpcVM
	(*GrpcStatus)(nil),    // 2: cache.GrpcStatus
	(*GrpcVMStatus)(nil),  // 3: cache.GrpcVMStatus
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_cache_proto_depIdxs = []int32{
	3, // 0: cache.GrpcStatus.vmstatus:type_name -> cache.GrpcVMStatus
	4, // 1: cache.CacheService.Config:input_type -> google.protobuf.Empty
	4, // 2: cache.CacheService.GetBaseVM:input_type -> google.protobuf.Empty
	4, // 3: cache.CacheService.Status:input_type -> google.protobuf.Empty
	4, // 4: cache.CacheService.Quit:input_type -> google.protobuf.Empty
	0, // 5: cache.CacheService.Config:output_type -> cache.GrpcVMConfig
	1, // 6: cache.CacheService.GetBaseVM:output_type -> cache.GrpcVM
	2, // 7: cache.CacheService.Status:output_type -> cache.GrpcStatus
	4, // 8: cache.CacheService.Quit:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
