apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    app: ping-test
spec:
  runtimeClassName: kata-qemu
  nodeName: ${NODE_NAME}
  ${HOST_NETWORK}
  containers:
  - name: nginx
    image: registry.k8s.io/pause:3.10.1
    ports:
    - containerPort: 80
${VOLUME_MOUNTS_SECTION}
${VOLUMES_SECTION}
