kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/vhost-vsock
    containerPath: /dev/vhost-vsock
  - hostPath: /dev/vhost-net
    containerPath: /dev/vhost-net
- role: worker
  extraMounts:
  - hostPath: /dev/vhost-vsock
    containerPath: /dev/vhost-vsock
  - hostPath: /dev/vhost-net
    containerPath: /dev/vhost-net

kubeadmConfigPatches:
- |
  kind: KubeletConfiguration
  runtimeRequestTimeout: "10m"
