apiVersion: v1
kind: Pod
metadata:
  name: kata-src
  labels:
    app: ping-target
spec:
  runtimeClassName: kata-qemu
  nodeSelector:
    katamaran-role: source
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
